alembic==1.4.2
appdirs==1.4.3
astroid==2.4.1
blinker==1.4
certifi==2020.4.5.1
chardet==3.0.4
click==6.7
colorama==0.4.3
distlib==0.3.0
filelock==3.0.12
Flask==1.0.2
Flask-Dance==0.14.0
Flask-DebugToolbar==0.10.1
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Migrate==2.1.1
Flask-OAuth==0.12
Flask-OAuthlib==0.9.4
Flask-SQLAlchemy==2.4.1
Flask-Uploads==0.2.1
Flask-WTF==0.14.2
httplib2==0.11.3
idna==2.6
isort==4.3.21
itsdangerous==0.24
Jinja2==2.10
lazy==1.3
lazy-object-proxy==1.4.3
Mako==1.1.2
MarkupSafe==1.0
mccabe==0.6.1
oauth2==1.9.0.post1
oauthlib==2.0.7
Pillow==7.1.2
pylint==2.5.2
python-dateutil==2.7.2
python-editor==1.0.3
requests==2.18.4
requests-oauthlib==0.8.0
six==1.14.0
SQLAlchemy==1.3.17
SQLAlchemy-Utils==0.33.2
toml==0.10.1
urllib3==1.22
URLObject==2.4.3
virtualenv==20.0.20
Werkzeug==0.14.1
wincertstore==0.2
wrapt==1.12.1
WTForms==2.1